std_msgs/Header header
int32 light_state

#light_state	Meaning
# 0	            White
# 1	            Blue / Flash
# 2	            Blue / Flash
# 3	            Purple
# 4	            Red / Flash
# 5	            Yellow
# 6	            Yellow
# 7	            Red
# 8	            Green
# 9	            Red / Slow-flash
# 10	        Off
# 11	        Blue
# 12	        Blue / Slow-flash
# 13	        White / Fast-flash